
extend type Mutation {
  insertTextualSysMLv2(input: InsertTextualSysMLv2Input!): InsertTextualSysMLv2Payload!
  updateElement(input: UpdateElementInput!): UpdateElementPayload!
}

input InsertTextualSysMLv2Input {
  id: ID!
  editingContextId: ID!
  objectId: ID!
  textualContent: String!
}

union InsertTextualSysMLv2Payload = ErrorPayload | SuccessPayload

input UpdateElementInput {
  id: ID!
  editingContextId: ID!
  elementId: ID!
  newLabel: String
  newShortName: String
  newBody: String
  properties: [KeyValueInput!]
}

input KeyValueInput {
  key: String!
  value: String!
}

union UpdateElementPayload = ErrorPayload | SuccessPayload
