package org.eclipse.syson.auth.model;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_PASSWORD_CHANGED,
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_DEACTIVATED,
    ADMIN_USER_REACTIVATED,
    ADMIN_PASSWORD_RESET,
    ADMIN_ROLE_ASSIGNED,
    ADMIN_ROLE_REMOVED,
    ADMIN_PROJECT_ROLE_GRANTED,
    ADMIN_PROJECT_ROLE_REVOKED,
    ADMIN_ELEMENT_PERMISSION_GRANTED,
    ADMIN_ELEMENT_PERMISSION_REVOKED,
    ACCESS_DECISION
}
